# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.11-slim

# Install build backend and runtime dependencies
RUN pip install --no-cache-dir hatchling

WORKDIR /app
# Copy project files
COPY pyproject.toml .
COPY uv.lock .
COPY src ./src
COPY README.md .

# Install the package
RUN pip install --no-cache-dir .

# Default entrypoint
ENTRYPOINT ["aci-mcp"]
